import sys
from datetime import datetime
import botocore
sys.path.append( '../')
from common.args import cloudwatch_logs_args  ## This is the only variable we should be importing from the args module and pass it to the functions below
from common.boto_client_declaration import cloudwatch_logs_client
from common.banners import operation_start_msg, outcome_banner

args, logs = cloudwatch_logs_args(), cloudwatch_logs_client(cloudwatch_logs_args())

def cloudwatch_delete_log_groups(args):
    f"""
    Calls the necessary functions to delete a given CloudWatch log group.\n

    Example
    -------
    cloudwatch_delete_log_groups(cloudwatch_logs_args_call)

    Parameters
    ------------
        args: argparse.Namespace\n
        The argparse generated by the ../common/args.py script, the best this is to import the 'cloudwatch_logs_args_call' variable from it.
    """
    start_time = datetime.now()
    print(args)
    # action, resource = "'Delete CloudWatch'", "group(s)"
    # operation_start_msg(action, args.group_name, resource)
    # print(list_bucket_objects(args)) ## For testing purposes
    # return_code = delete_bucket_objects_excecution(list_bucket_objects(args)) ## Objects are remove with this call
    total_time =  datetime.now() - start_time
    # outcome_banner(action, args.bucket, resource, return_code, total_time)
    # return None


if __name__ == "__main__":
    cloudwatch_delete_log_groups(args)
    # delete_bucket_objects_excecution()
